## Cargar, mostrar, proporcionar y crear imagenes

In [1]:
import cv2

img = cv2.imread("galaxy.jpg", 0) # 0 para BN, 1 para RGB, -1 para RGB Transparente
print(type(img)) # el tipo es un array de Numpy
print(img) # nos imprime un array
print(img.shape) # la resolucion
print(img.ndim) # dimensiones

<class 'numpy.ndarray'>
[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]
(1485, 990)
2


### Leer imagen

In [2]:
cv2.imshow("Galaxy", img) # Visualizar la imagen. Parametros: NombreTitulo, Array del archivo
cv2.waitKey(0)
cv2.destroyAllWindows()

### Cambiar la proporción de una imagen

In [3]:
resized_image = cv2.resize(img, (int(img.shape[1]/2), int(img.shape[0]/2))) # parametros: array, (height, widht)
cv2.imshow("Galaxy", resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Crear una imagen (a partir de la imagen resized)

In [4]:
cv2.imwrite("Galaxy_resized.jpg", resized_image)

True