## Numpy
Biblioteca usada para realizar operaciones en arreglos multidimensionales.
Trabaja con Arrays, una lista que contiene listas con la misma cantidad de elementos c/u.
Un array es similar a una lista, pero se diferencian en un bajo nivel.

Con dimensión, nos referimos a la arquitectura del arreglo. Es decir, 1 dimensión refiere a una fila, 2 dimensiones a que se compone por filas y columnas. 

In [1]:
import numpy

In [3]:
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

(3, 9) significa:
- 3 filas (listas)
- 9 columnas (elementos de la lista)

In [8]:
n.reshape(3, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [9]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
b = numpy.asarray([[232, 12, 1233, 12], [323, 12, 123, 55], [123, 123, 55, 53]])

b

array([[ 232,   12, 1233,   12],
       [ 323,   12,  123,   55],
       [ 123,  123,   55,   53]])