Para traer una porción de array, debemos hacerlo usando la indexación

In [1]:
import cv2

In [8]:
import numpy

In [2]:
im_g = cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

De las primeras 2 listas, trae los elementos 3ro y 4to

In [3]:
im_g[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

Traemos, de la 3er fila, el último elemento (la última columna)

In [4]:
im_g[2, 4]

182

### Iteración
Iteración de cada línea

In [5]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


Iteración de cada columna (arreglo traspuesto)

In [6]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


Iteración valor por valor (todos los elementos)

In [7]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


Concatenar 2 arreglos (el arreglo será el mismo concatenado con el mismo)

In [10]:
ims = numpy.hstack((im_g, im_g))
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


Se concatena la primer lista con la otra primer lista, y así correspondientemente

Ahora, de forma vertical

In [11]:
ims2 = numpy.vstack((im_g, im_g))
print(ims2)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


Separar arreglos

In [26]:
lst = numpy.vsplit(ims, 3)
lst

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]

In [21]:
lst2 = numpy.vsplit(ims2, 2)
lst2

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]